config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :kittens

  root 'kittens#index'  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
	validates :name, presence: true, length: { maximum: 50 }
	validates :age, presence: true, :inclusion => 1..30
	validates :cuteness, presence: true, :inclusion => 1..10
	validates :softness, presence: true, :inclusion => 1..10
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
	def index
		@kittens = Kitten.all.order(created_at: :desc)
		respond_to do |format|
	        format.html # index.html.erb
	        format.xml  { render :xml => @kittens }
	        format.json { render :json => @kittens }
        end
	end

	def new
		@kitten = Kitten.new
	end

	def create
		@kitten = Kitten.create!(kitten_params)
		if @kitten.save
			flash[:success] = "Kitten was created successfully"
			redirect_to kitten_path(@kitten)
		else
			flash.now[:danger] = "Your kitten could not be created."
			render 'new'
		end
	end

	def show
		@kitten = Kitten.find(params[:id])
		respond_to do |format|
	        format.html # show.html.erb
	        format.xml  { render :xml => @kitten }
	        format.json { render :json => @kitten }
        end		
	end

	def destroy
		Kitten.find(params[:id]).destroy
		flash[:success] = "Kitten Deleted.  Now, why would you want to do that?"
		redirect_to root_url
	end

	def edit
		@kitten = Kitten.find(params[:id])
	end

	def update
		@kitten = Kitten.find(params[:id])
		if @kitten.update_attributes(kitten_params)
			flash[:success] = "Kitten Updated Successfully!"
			redirect_to kitten_path(@kitten)
		else
			flash.now[:danger] = "Cannot Update Kitten"
			render 'edit'
		end
	end

	private

	def kitten_params
		params.require(:kitten).permit(:name, :age, 
			:cuteness, :softness)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_kitty_form.html.erb
<div id="main_form">
  <%= form_for(@kitten) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :name %><br/ >
    <%= f.text_field :name %><br/ ><br/ >

    <%= f.label :age %><br/ >
    <%= f.number_field :age, in: 1..30 %><br/ ><br/ >

    <%= f.label :cuteness %><br/ >
    <%= f.number_field :cuteness, in: 1..10 %><br/ ><br/ >

    <%= f.label :softness %><br/ >
    <%= f.number_field :softness, in: 1..10 %><br/ ><br/ >

    <%= f.submit("Submit") %>
  <% end %>
</div>

app/views/kittens/edit.html.erb
<h1>Edit Kitty</h1>

<%= render 'kitty_form' %>
<br/ > <br/ >

<div id="delete_link"><%= link_to "Delete #{@kitten.name}?", @kitten, method: :delete,data: { confirm: "You sure?"} %></div>

app/views/kittens/index.html.erb
<h1>All Kittens</h1>

<table id="kitty_table">
	<thead>
		<tr>
			<th>Name</th>
			<th>Age</th>
			<th>Cuteness</th>
			<th>Softness</th>
			<th>Created At</th>
			<th>Edit</th>
			<th>Delete</th>
		</tr>
	</thead>
	<tbody>
		<% @kittens.each do |kitten| %>
			<tr>
				<td><%= link_to "#{kitten.name}", kitten %></td>
				<td><%= kitten.age %></td>
				<td><%= kitten.cuteness %></td>
				<td><%= kitten.softness %></td>
				<td><%= kitten.created_at.strftime("%m/%d/%Y %l:%M:%S %p")  %></td>
				<td><%= link_to "edit", edit_kitten_path(kitten) %></td>
				<td><%= link_to "delete", kitten, method: :delete,
					data: { confirm: "You sure?"} %></td>

			</tr>
		<% end %>
	</tbody>
</table>

app/views/kittens/new.html.erb
<h1>Create New Kitty</h1>

<%= render 'kitty_form' %>

app/views/kittens/show.html.erb
<h1 id="show_id"><%= @kitten.name.capitalize %></h1><br/ >
<div class="kitty_details">
	<strong>Age:</strong><%= @kitten.age %><br/ >
	<strong>Cuteness:</strong><%= @kitten.cuteness %><br/ >
	<strong>Softness:</strong><%= @kitten.softness %><br/ ><br/ >
	<%= link_to "Delete #{@kitten.name}?", @kitten, method: :delete,data: { confirm: "You sure?"} %>
</div>

app/views/layouts/_footers.html.erb
<footer class="footer">
  <small>
    By <a href="https://github.com/dvislearning">DV</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Project Repository",   '#' %> || <%= link_to "Find me on GitHub",   'https://github.com/dvislearning' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_headers.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "kittens!", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "All Kittens", root_path %></li>
        <li><%= link_to "New Kitten", new_kitten_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/headers' %>
  </head>

  <body>
      <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>    	
    <%= yield %>
    <%= render 'layouts/footers' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>